platform :ios, '9.3'
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
target 'SSS Freshman App' do
    pod 'GoogleAPIClient/Core', '~> 1.0.2'
    pod 'GTMOAuth2', '~> 1.1.0'
    pod 'GoogleMaps', '~> 2.0'
    pod 'RealmSwift', '~> 1.0'
    pod 'GoogleAPIClient/Calendar', '~> 1.0.2'
    pod 'FSCalendar', '~> 2.3'
    pod 'Google/Analytics'
end
